---
- name: Hello World!
  hosts: all
  gather_facts: true
  tasks:

  - name: Hello World!
    shell: echo "Hi! {{ lookup('env', 'logged_in_user') }} !!!!!!!!!!!!!!!!  {{ lookup('env', 'facts') }} Tower is working!"
    
  - name: Printing all the environment​ variables in Ansible
    debug:
      msg: "{{ ansible_env }}"
      
  - name: Printing extra variables in Ansible
    debug:
      msg: "{{ logged_in_user }}"
      
  - name: Printing extra variables from jenkin in Ansible
    debug:
      msg: "{{ logged_in_from_jenkin }}"

  - name: Printing environment variable
    debug:
      msg: "{{ facts }}"
