---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! {{ lookup('env', 'logged_in_user') }} !!!!!!!!!!!!!!!! {{ ansible_env.logged_in_user }} Tower is working!"
